In [43]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore') 
import statistics as stats

In [44]:
shar_tack = pd.read_csv("/Users/lcorrea/Desktop/sharckattack/attacks.csv",sep=',', encoding='latin-1')

In [45]:
shar_tack.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [74]:
shar_tack.shape

(2808, 24)

In [73]:
#shar_tack.describe().T

In [46]:
print(shar_tack.columns)

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [47]:
shar_tack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25723 entries, 0 to 25722
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             8702 non-null   object
 1   Date                    6302 non-null   object
 2   Year                    6300 non-null   float64
 3   Type                    6298 non-null   object
 4   Country                 6252 non-null   object
 5   Area                    5847 non-null   object
 6   Location                5762 non-null   object
 7   Activity                5758 non-null   object
 8   Name                    6092 non-null   object
 9   Sex                     5737 non-null   object
 10  Age                     3471 non-null   object
 11  Injury                  6274 non-null   object
 12  Fatal (Y/N)             5763 non-null   object
 13  Time                    2948 non-null   object
 14  Species                 3464 non-null   object
 15  Investigator or Source  6285 non-null   object
 16  pdf                     6302 non-null   object
 17  href formula            6301 non-null   object
 18  href                    6302 non-null   object
 19  Case Number.1           6302 non-null   object
 20  Case Number.2           6302 non-null   object
 21  original order          6309 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             2 non-null      object
dtypes: float64(2), object(22)
memory usage: 4.7+ MB

In [61]:
from datetime import datetime


shar_tack.rename(columns = {'Sex ':'Sex', 'Species ':'Species'}, inplace = True)
# Date convertions
shar_tack['Date'] = pd.to_datetime(shar_tack['Date'], errors='coerce')
shar_tack['Case Number'] = pd.to_datetime(shar_tack['Case Number'], errors='coerce')
shar_tack['Year'] = pd.to_numeric(shar_tack['Year'], errors='coerce', downcast="integer")
shar_tack['Age'] = pd.to_numeric(shar_tack['Age'], errors='coerce')
shar_tack['Case Number.1'] = pd.to_datetime(shar_tack['Case Number'], errors='coerce')
shar_tack['Case Number.2'] = pd.to_datetime(shar_tack['Case Number'], errors='coerce')


shar_tack.astype({
    'Type':'string',
    'Country':'string',
    'Area':'string',
    'Location':'string',
    'Activity':'string',
    'Name':'string',
    'Sex':'string',
    'Species':'string',
    'Injury':'string',
    'Fatal (Y/N)':'string',
    'Investigator or Source':'string',
    'pdf':'string',
    'href formula':'string',
    'href':'string',
    'Time':'string'
}).dtypes

Case Number               datetime64[ns]
Date                      datetime64[ns]
Year                               int16
Type                              string
Country                           string
Area                              string
Location                          string
Activity                          string
Name                              string
Sex                               string
Age                              float64
Injury                            string
Fatal (Y/N)                       string
Time                              string
Species                           string
Investigator or Source            string
pdf                               string
href formula                      string
href                              string
Case Number.1             datetime64[ns]
Case Number.2             datetime64[ns]
original order                   float64
Unnamed: 22                       object
Unnamed: 23                       object
dtype: object

In [62]:
shar_tack.drop_duplicates(inplace=True)

In [63]:
shar_tack.shape

(2808, 24)

In [64]:
nan_cols = shar_tack.isna().sum()

In [65]:
nan_cols

Case Number                 0
Date                       15
Year                        0
Type                        0
Country                     0
Area                        0
Location                    0
Activity                    0
Name                        0
Sex                         0
Age                       585
Injury                      0
Fatal (Y/N)                 0
Time                        0
Species                     0
Investigator or Source      0
pdf                         0
href formula                0
href                        0
Case Number.1               0
Case Number.2               0
original order              0
Unnamed: 22                 0
Unnamed: 23                 0
dtype: int64

In [66]:
# Keep rows that contain at least 2 non-missing values
shar_tack.dropna(axis=0, thresh=20, inplace = True)

In [67]:
shar_tack.replace({pd.NaT: 'None'}, inplace=True)
shar_tack.fillna('None', inplace = True)

In [68]:
shar_tack

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018-06-25,2018-06-25 00:00:00,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018-06-25,2018-06-25,6303.0,None,None
1,2018-06-18,2018-06-18 00:00:00,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,None,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018-06-18,2018-06-18,6302.0,None,None
2,2018-06-09,2018-06-09 00:00:00,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,None,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018-06-09,2018-06-09,6301.0,None,None
3,2018-06-08,2018-06-08 00:00:00,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018-06-08,2018-06-08,6300.0,None,None
4,2018-06-04,2018-06-04 00:00:00,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018-06-04,2018-06-04,6299.0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6239,2068-01-01,None,0,Unprovoked,MOZAMBIQUE,Maputo Province,Santa Maria Peninsula,Skindiving,Les Bishop,M,...,"""A pack of sharks""",L. Bishop; V.M. Coppleson (1962),ND-0068-LesBishop.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2068-01-01,2068-01-01,64.0,None,None
6241,2065-01-01,None,0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Fishing from a small boat & put his hand in th...,male,M,...,None,B.W. Coad & L.A.J. Al-Hassan,ND-0065-deadfish.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2065-01-01,2065-01-01,62.0,None,None
6242,2064-01-01,None,0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River,Swimming naked near a date palm where many dat...,male,M,...,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0064-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2064-01-01,2064-01-01,61.0,None,None
6243,2063-01-01,None,0,Unprovoked,IRAQ,Basrah,Shatt-al-Arab River near Abu al Khasib,Swimming in section of river used for washing ...,male,M,...,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0063-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2063-01-01,2063-01-01,60.0,None,None
6265,2038-01-01,None,0,Unprovoked,IRAQ,Basrah,Shatt-el Arab River near a small boat stand,Swimming,male,M,...,Bull shark,B.W. Coad & L.A.J. Al-Hassan,ND-0038-Shatt-al-Arab.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2038-01-01,2038-01-01,38.0,None,None

In [69]:
shar_tack.to_csv('shar_tack.csv', index = True)